BL-13601 receive text message with authentication code
dvsa/motr pull request #101
Opened 2022-06-28 13:33 UTC by shibuzgeorge

2022-06-29 10:30 UTC, mateuszc-kainos requested changes

2022-06-29 10:30 UTC, mateuszc-kainos commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/component/subscription/service/SmsConfirmationManageService.java
> +                        new SmsConfirmationCreatedEvent().setPhoneNumber(phoneNumber).setConfirmationCode(confirmationCode));
I think we should create a separate event for SmsConfirmationManage, e.g. SmsConfirmationManageCreatedEvent

2022-06-29 10:30 UTC, mateuszc-kainos commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/component/subscription/service/SmsConfirmationManageService.java
> +                        new SmsConfirmationCreatedEvent().setPhoneNumber(phoneNumber).setConfirmationCode(confirmationCode));
See above comment

2022-06-29 10:30 UTC, mateuszc-kainos commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/component/subscription/service/SmsConfirmationManageService.java
> +            throw e;
See above comments

2022-06-29 10:30 UTC, mateuszc-kainos commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/component/subscription/service/SmsConfirmationManageService.java
> +                    EventLogger.logEvent(new InvalidSmsConfirmationIdUsedEvent().setUsedId(confirmationId).setPhoneNumber(phoneNumber));
See above comments

2022-06-29 10:30 UTC, mateuszc-kainos commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/component/subscription/service/SmsConfirmationManageService.java
> +public class SmsConfirmationManageService {
There seems to be a lot of duplication and similarities to SmsConfirmationService - can we somehow use the common code and make it cleaner? Some kind of flag that would tell us which path we are taking - SmsConfirmation or SmsConfirmationManage - that would then influence which repositories, notifytemplates, etc. should be used?

2022-06-29 10:30 UTC, mateuszc-kainos commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/resource/CheckYourPhoneResource.java
> +
Double whitespace

2022-06-30 09:04 UTC, shibuzgeorge commented on motr-webapp/webapp/src/main/java/uk/gov/dvsa/motr/web/component/subscription/service/SmsConfirmationManageService.java
> +public class SmsConfirmationManageService {
Tried adding flag checks to SmsConfirmationService to make it one class but there is still changes in SmsConfirmationManage that cannot be used for both - such as not needing the confirmation id session and also generating new security code each time they click resend. It didn't make much of a difference, just made it harder to read

2022-06-30 10:19 UTC, mateuszc-kainos approved these changes

2022-07-01 07:17 UTC, aaronddvsa approved these changes

2022-07-05 14:43 UTC, merged