BL-14689 Insert recalls feature toggle
dvsa/motr pull request #147
Opened 2023-04-17 13:35 UTC by mateuszc-kainos

## Description

Create recalls feature toggle

Related issue: [BL-14689](https://dvsa.atlassian.net/browse/BL-14689)

## Before submitting (or marking as "ready for review")

- [v] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [v] Have you performed a self-review of the code
- [v] Have you have added tests that prove the fix or feature is effective and working
- [v] Did you make sure to update any documentation relating to this change?

2023-04-17 13:47 UTC, michaelbkainos approved these changes

2023-04-17 14:07 UTC, shibuzgeorge commented
RECALLS_FEATURE_TOGGLE should be added to template.yaml and .env.example

2023-04-18 08:28 UTC, shibuzgeorge approved these changes

2023-04-27 14:41 UTC, aaronlong requested changes
Overall looks good, just two test names to update to be more representative of what the test is doing.  :)

2023-04-27 14:41 UTC, aaronlong commented on motr-notifier/src/test/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionServiceTest.java
> +    public void whenVehicleExpiryDateIsInOneMonthAndOutstandingRecallSmsReminderIsSentWhenRecallsToggleIsOff() throws Exception {
Same here as above, just test name update to 'NotSent'

2023-04-27 15:20 UTC, aaronlong approved these changes

2023-04-27 15:24 UTC, merged