BL-14688 MOTR still send MOT Reminders if Recalls API call fails
dvsa/motr pull request #152
Opened 2023-05-04 14:09 UTC by shibuzgeorge

## Description

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2023-05-04 15:47 UTC, aaronlong requested changes

2023-05-04 15:47 UTC, aaronlong commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionService.java
> +        return new RecallDetails();
Can we check unit test coverage here to make sure this case is covered :)

2023-05-05 10:20 UTC, shibuzgeorge commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionService.java
> +        return new RecallDetails();
Done

2023-05-05 10:49 UTC, DariuszJerzewski requested changes
Looks good, but left some suggestions.

2023-05-05 10:49 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionService.java
>              logger.debug("Could not get recalls for vehicle with vrm {}", vehicleVrm);
I'd change the log level to warn/error here.

2023-05-05 10:49 UTC, DariuszJerzewski commented on motr-common/src/main/java/uk/gov/dvsa/motr/recalldetails/RecallDetails.java
>          return Arrays.stream(this.recalls).anyMatch(recall -> RecallStatus.isOutstanding(recall.getRepairStatus()));
Can we get an optional of `this.recalls` - this removes the if?

```
return Arrays.stream(Optional.ofNullable(this.recalls).orElse(new String[0])).anyMatch(recall -> RecallStatus.isOutstanding(recall.getRepairStatus()));
```

2023-05-05 10:49 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionService.java
>              logger.debug("Could not get recalls for vehicle with vrm {}", vehicleVrm);
Can you also add exception details? We want to capture the reason for failure as well.

2023-05-09 09:13 UTC, DariuszJerzewski commented on motr-common/src/main/java/uk/gov/dvsa/motr/recalldetails/RecallDetails.java
>          return Arrays.stream(this.recalls).anyMatch(recall -> RecallStatus.isOutstanding(recall.getRepairStatus()));
nice :)

2023-05-09 12:52 UTC, DariuszJerzewski approved these changes

2023-05-25 11:23 UTC, aaronlong approved these changes

2023-05-26 15:51 UTC, merged