feat: update content on privacy notice
dvsa/motr pull request #155
Opened 2023-07-03 09:01 UTC by caoimheb

## Description

Update content and styling on privacy notice

Related issue: [BL-14909](https://dvsa.atlassian.net/browse/BL-14909)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2023-07-03 13:52 UTC, aaronlong approved these changes

2023-07-04 11:38 UTC, DariuszJerzewski requested changes

2023-07-04 11:38 UTC, DariuszJerzewski commented on motr-webapp/webapp/src/main/resources/template/privacy-notice.hbs
> +            <h2 class="gem-c-contents-list__title">Updated 30 June 2023</h2>
The styles should be replaced by govuk classes preferably. @jennifer-choo is working on similar PR in one of the other repositories.

2023-07-10 08:16 UTC, DariuszJerzewski approved these changes

2023-07-13 14:24 UTC, merged