BL-14813 Send MOTR Prompt Notification
dvsa/motr pull request #159
Opened 2023-07-14 11:37 UTC by shibuzgeorge

## Description

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2023-07-17 11:20 UTC, DariuszJerzewski requested changes
@shibuzgeorge  could you update the checklist and PR title to follow the conventional commits spec?

2023-07-17 11:28 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/model/SubscriptionQueueItem.java
> +    public Boolean getHasV5cChanged() {
Just wanted to double-check - did you add a test where the 'hasV5cChanged' field is missing from the message body? 

This is to make sure the current payload from subscription-loader lambda, will work as expected.

2023-07-17 11:31 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/factory/SendableNotificationFactory.java
> +        if (subscription.getHasV5cChanged() != null && subscription.getHasV5cChanged()) {
Could you add a check here to see if the V5C reference in the payload is different from the V5C reference in DynamoDB?

2023-07-17 11:31 UTC, shibuzgeorge commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/model/SubscriptionQueueItem.java
> +    public Boolean getHasV5cChanged() {
The other tests doesn't include the hasV5cChanged and it passes fine

2023-07-17 11:43 UTC, DariuszJerzewski commented on motr-webapp/webapp/src/main/resources/template/notify/prompt/prompt-email-body.txt
> +You can view and manage your MOT reminders at https://www.gov.uk/mot-reminder
I think it could be configurable instead - will be easier to change this way. Or is there a reason why it was removed to be a hardcoded link?

2023-07-17 12:01 UTC, shibuzgeorge commented on motr-webapp/webapp/src/main/resources/template/notify/prompt/prompt-email-body.txt
> +You can view and manage your MOT reminders at https://www.gov.uk/mot-reminder
I assumed it will be the same link but I will make it configurable

2023-07-19 14:22 UTC, jennifer-choo approved these changes

2023-07-20 13:19 UTC, faggc commented
@shibuzgeorge have you resolved the previous comments from @DariuszJerzewski

2023-07-20 13:25 UTC, shibuzgeorge commented
> @shibuzgeorge have you resolved the previous comments from @DariuszJerzewski

Yes resolved

2023-07-20 13:39 UTC, faggc approved these changes

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/factory/SendableNotificationFactory.java
> +
Extra whitespace.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/factory/SendableNotificationFactory.java
> +
Extra whitespace.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/model/SubscriptionQueueItem.java
> +    @JsonProperty("v5cReference")
This can be removed.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/model/SubscriptionQueueItem.java
> +    public String getV5cReference() {
This can be removed.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/model/SubscriptionQueueItem.java
> +    public SubscriptionQueueItem setV5cReference(String v5cReference) {
This can be removed.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionService.java
> +    private boolean checkV5cReferences(SubscriptionQueueItem subscriptionInPayLoad, SubscriptionDbItem subscriptionInDb) {
This can be removed - my bad, it will be already checked at this point! The v5cChanged flag is only required here to make sure a correct notification type is sent.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/component/subscription/persistence/DynamoDbSubscriptionRepository.java
> +        if (item.isPresent("v5c_reference")) {
This can be removed.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/component/subscription/persistence/DynamoDbSubscriptionRepository.java
> +            if (originalItem.isPresent("v5c_reference")) {
This can be removed.

2023-07-21 07:34 UTC, DariuszJerzewski commented on motr-subscription-loader/src/main/java/uk/gov/dvsa/motr/subscriptionloader/processing/model/Subscription.java
> +    public String getV5cReference() {
This should be removed here, this property should be ignored if not part of the class and it should work as it did previously.

2023-07-21 07:57 UTC, shibuzgeorge commented on motr-notifier/src/main/java/uk/gov/dvsa/motr/notifier/processing/service/ProcessSubscriptionService.java
> +    private boolean checkV5cReferences(SubscriptionQueueItem subscriptionInPayLoad, SubscriptionDbItem subscriptionInDb) {
I don't understand I thought we had to check the the v5c reference in the payload and the DB? This method checks if it matches or not

2023-07-25 10:16 UTC, DariuszJerzewski approved these changes

2023-07-28 08:39 UTC, merged